### PR TITLE
Add inhibited trigger counter to operational monitoring

### PR DESCRIPTION
**Pull request by eflumerf**

### CODE REVIEW

**Comment by philiprodrigues** [comment]
From a code style point of view, everything looks good. There are two cases included in the count here, and I wonder if they should be separated:
1. Triggers not sent because of lack of tokens
2. Triggers not sent because triggers were paused
A possible reason to separate them is so that a "clean" run in which we never run out of tokens gets an "inhibited" count of 0. As it stands, you could get a nonzero inhibited count from the triggers that would have been issued between "start" and "resume", even if tokens never run out.

Or, easier than separating them would just be to not include case 2, on the thinking that it's a less interesting quantity from the point of view of understanding whether things are working. What do you think?

**Comment by bieryAtFnal** [comment]
I vote for excluding missed-triggers-because-the-TDE-is-paused.

**Comment by eflumerf** [comment]
I've removed the second set, so only triggers inhibited due to lack of tokens are counted.

**Review by philiprodrigues — APPROVED** [review]
LGTM. I tested with 0 tokens and see the inhibited counts increasing as I expect. With 10 initial tokens, the inhibited counts remain at 0

**Pull request merged**
